# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 490991f5fb3c78abf0bfdfe3991aebc28b44d99ccd71a9c38beb5930964a4855ec87d466ff7954ed3aa5c12f15aba27a756a3338a1e2a6c828ab9529281578bd

test:
  secret_key_base: fc8df0d0faa066b188c025ea34d691d4693717c436395ff1cef892d32676def2c6d4fa8abf686eba229e2eb9b3af8b7dc91c2f5b2e4316fb020cf1896940fdb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
